

name: SVNBox

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        
      - uses: docker/build-push-action@v2
        id: docker_build
        name: Build docker image
        with:
          context: ./tests/custom_svn_box
          file: ./tests/custom_svn_box/Dockerfile
          push: false
          tags: rsvn_box
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Run Server
        run: docker run -p 3690:3690 ${{ steps.docker_build.outputs.digest }} 
    
      - name: Run Svn command
        run: svn co svn://localhost:3690/Test Test
