

name: SVNBox

on: [push]



jobs:
  svn-job:
    runs-on: ubuntu-latest
    services:
      image: elleflorio/svn-server
      

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
    
      - name: Run Svn command
        run: svn co svn://localhost:3690/Test Test


    needs: [svn-job]
